'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { BlogRecord, BlogInput, MediaOption } from '@/lib/cms/types';
import { api, Icon, Message, thumbnail, useUnsaved } from './ui';
import { MediaPicker } from './MediaPicker';
export function BlogList({ posts, photos }: { posts: BlogRecord[]; photos: MediaOption[] }) {
  const [trash,setTrash]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();
  const filtered=posts.filter(p=>p.deleted===trash&&p.draft.title.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
  return <><div className="admin-page-title"><div><h1>Blog yazıları</h1><p>Yazılarınızı hazırlayın, önizleyin ve yayınlayın.</p></div><button className="admin-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const p=await api<BlogRecord>('blog','POST');router.push(`/admin/blog/${p.id}`);}catch(e){setError((e as Error).message);setBusy(false);}}}><Icon name="plus"/>Yeni yazı</button></div><Message error={error}/><div className="admin-toolbar"><label className="admin-search"><span className="visually-hidden">Yazı ara</span><input placeholder="Yazı ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="admin-secondary" onClick={()=>setTrash(!trash)}>{trash?'← Yazılara dön':`Çöp kutusu (${posts.filter(p=>p.deleted).length})`}</button></div><div className="admin-project-grid">{filtered.map(p=>{const cover=photos.find(photo=>photo.id===p.draft.coverId);return <article key={p.id} className="admin-project-card"><Link href={`/admin/blog/${p.id}`} className="admin-project-cover" aria-label={`${p.draft.title} yazısını düzenle`}>{cover?<img src={thumbnail(cover.image.src)} alt="" loading="lazy"/>:<span><Icon name="image"/>Kapak seçilmedi</span>}</Link><div className="admin-project-caption"><h2><Link href={`/admin/blog/${p.id}`}>{p.draft.title}</Link></h2><p>{p.deleted?'Çöp kutusunda':!p.published?'Taslak':JSON.stringify(p.draft)!==JSON.stringify(p.published)?'Yayında · Yeni değişiklikler taslakta':'Yayında'}</p></div></article>;})}</div>{!filtered.length&&<div className="admin-empty"><p>{trash?'Çöp kutusu boş.':'Henüz yazı yok.'}</p></div>}</>;
}
function inputOf(p: BlogRecord): BlogInput { const {title,excerpt,body,coverId}=p.draft;return {title,excerpt,body,coverId}; }
export function BlogEditor({ initial, photos }: { initial: BlogRecord; photos: MediaOption[] }) {
  const [record,setRecord]=useState(initial),[data,setData]=useState(inputOf(initial)),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const router=useRouter(),text=useRef<HTMLTextAreaElement>(null);
  const changed=JSON.stringify(data)!==JSON.stringify(inputOf(record));useUnsaved(changed||busy);
  const cover=photos.find(p=>p.id===data.coverId);
  function edit<K extends keyof BlogInput>(key:K,value:BlogInput[K]){setData(d=>({...d,[key]:value}));setMessage('');}
  async function action(path:string,method:string,payload:unknown,notice:string){if(busy)return;setBusy(true);setError('');setMessage('');try{const p=await api<BlogRecord>(`blog/${record.id}${path}`,method,payload);setRecord(p);setData(inputOf(p));setMessage(notice);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function state(kind:'unpublish'|'trash'|'restore'){const question=kind==='trash'?'Yazı çöp kutusuna taşınsın mı? Daha sonra geri alabilirsiniz.':kind==='unpublish'?'Yazı siteden kaldırılıp taslak olarak saklansın mı?':'Yazı taslak olarak geri alınsın mı?';if(window.confirm(question))action(`/${kind}`,'POST',{version:record.version},kind==='restore'?'Yazı taslağa geri alındı.':'Yazı siteden kaldırıldı.');}
  return <><Link href="/admin/blog" className="admin-back">← Blog yazıları</Link><div className="admin-page-title"><div><h1>{record.draft.title}</h1><p>{record.deleted?'Bu yazı çöp kutusunda.':record.published?'Yazı yayında. Kaydettiğiniz taslak, tekrar yayınlayana kadar sitede değişmez.':'Yazı henüz yayında değil.'}</p></div></div><div className="admin-editor-actions"><span>{busy?'Kaydediliyor…':changed?'Kaydedilmemiş değişiklikler':'Tüm değişiklikler kaydedildi'}</span>{!record.deleted&&<div><a href={`/admin/blog-onizleme/${record.id}`} target="_blank" rel="noopener noreferrer" className="admin-secondary">Önizle ↗</a><button className="admin-secondary" disabled={busy||!changed} onClick={()=>action('','PUT',{version:record.version,data},'Taslak kaydedildi.')}>Taslağı kaydet</button><button className="admin-primary" disabled={busy} onClick={()=>action('/publish','POST',{version:record.version,data},'Yazı yayınlandı.')}>Yayınla <Icon name="arrow"/></button></div>}</div><Message error={error} message={message}/>
  {record.deleted?<section className="admin-box admin-empty"><p>Yazı metni korunuyor.</p><button className="admin-primary" disabled={busy} onClick={()=>state('restore')}>Yazıyı geri al</button></section>:<><div className="admin-editor-grid admin-blog-editor"><section className="admin-box admin-fields"><fieldset disabled={busy}><label>Başlık<input value={data.title} maxLength={160} required onChange={e=>edit('title',e.target.value)}/></label><label>Kısa giriş<textarea value={data.excerpt} maxLength={400} rows={3} onChange={e=>edit('excerpt',e.target.value)}/><small>Blog listesindeki kısa açıklama.</small></label><label htmlFor="blog-body">Yazı</label><div className="admin-writing-tools"><button type="button" className="admin-secondary" onClick={()=>{const el=text.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;edit('body',`${data.body.slice(0,start)}\n\n## ${data.body.slice(start,end)||'Ara başlık'}\n\n${data.body.slice(end)}`);el.focus();}}>Ara başlık ekle</button><small>Yeni paragraf için arada boş bir satır bırakın.</small></div><textarea id="blog-body" ref={text} className="admin-blog-body" value={data.body} maxLength={50000} rows={20} onChange={e=>edit('body',e.target.value)}/></fieldset><p className="admin-editor-hint">Önizleme, son kaydettiğiniz taslağı gösterir.</p></section><section className="admin-box admin-fields"><div className="admin-box-heading"><h2>Yazının kapağı</h2></div>{cover?<img className="admin-cover-preview" src={thumbnail(cover.image.src)} alt={cover.name}/>:<p className="admin-empty">Kapak fotoğrafı seçilmedi.</p>}<button className="admin-secondary" disabled={busy} onClick={()=>setPicker(true)}>Kapak görseli seç</button>{data.coverId&&<button className="admin-remove" disabled={busy} onClick={()=>edit('coverId','')}>Kapağı kaldır</button>}<p className="admin-editor-hint">Yayındaki proje fotoğraflarından seçebilirsiniz.</p>{record.published&&<a className="admin-secondary" href={`/blog/${record.published.slug}`} target="_blank" rel="noopener noreferrer">Yazıyı sitede gör ↗</a>}</section></div><div className="admin-editor-bottom"><span>{record.published&&<button className="admin-secondary" disabled={busy} onClick={()=>state('unpublish')}>Yayından kaldır</button>}</span><button className="admin-danger" disabled={busy} onClick={()=>state('trash')}>Çöp kutusuna taşı</button></div></>}
  {picker&&<MediaPicker title="Yazı kapağını seç" photos={photos} onClose={()=>setPicker(false)} onChoose={ids=>edit('coverId',ids[0])}/>}
  </>;
}
