'use client';
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { HomepageRecord, MediaOption, ProjectOption } from '@/lib/cms/types';
import { api, Icon, Message, thumbnail, useUnsaved } from './ui';
import { MediaPicker } from './MediaPicker';
export function Homepage({ initial, photos, projects }: { initial: HomepageRecord; photos: MediaOption[]; projects: ProjectOption[] }) {
  const [saved, setSaved] = useState(initial), [data, setData] = useState(initial.data), [picker, setPicker] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  const router = useRouter(), changed = JSON.stringify(data) !== JSON.stringify(saved.data);
  useUnsaved(changed);
  function move(key: 'slides' | 'projects', index: number, direction: number) { const list = [...data[key]], next = index + direction; if (next < 0 || next >= list.length) return; [list[index], list[next]] = [list[next], list[index]]; setData({ ...data, [key]: list }); setMessage(''); }
  async function save() { setBusy(true); setError(''); setMessage(''); try { const result = await api<HomepageRecord>('homepage', 'PUT', { version: saved.version, data }); setSaved(result); setData(result.data); setMessage('Ana sayfa güncellendi.'); router.refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="admin-page-title"><div><h1>Ana sayfa</h1><p>Açılış slaytındaki fotoğrafları ve altında gösterilecek proje kartlarını ayrı ayrı seçin.</p></div></div><div className="admin-editor-actions"><span>{changed ? 'Kaydedilmemiş değişiklikler' : 'Yayındaki ana sayfa seçimi'}</span><div><a href="/" target="_blank" rel="noopener noreferrer" className="admin-secondary">Siteyi görüntüle ↗</a><button className="admin-primary" disabled={busy || !changed} onClick={save}>{busy ? 'Kaydediliyor…' : 'Ana sayfayı güncelle'}</button></div></div><Message error={error} message={message}/>
  <section className="admin-box admin-home-section"><div className="admin-box-heading"><div><h2>Açılış fotoğrafları</h2><p>Bu sırayla otomatik değişir. En fazla 40 fotoğraf.</p></div><button className="admin-primary" disabled={busy || data.slides.length >= 40} onClick={() => setPicker(true)}><Icon name="plus"/>Fotoğraf seç</button></div><div className="admin-selection-grid">{data.slides.map((id,index) => { const photo = photos.find(p=>p.id===id); return <article key={id} className="admin-selection-card">{photo ? <img src={thumbnail(photo.image.src)} alt={photo.name}/> : <div className="admin-empty">Bu fotoğraf artık yayında değil.</div>}<div><strong>{index + 1}. {photo?.projectTitle || 'Kullanılamayan fotoğraf'}</strong><small>{photo?.name}</small><div className="admin-selection-actions"><button className="admin-secondary" disabled={busy || !index} aria-label={`${index+1}. fotoğrafı öne al`} onClick={()=>move('slides',index,-1)}>←</button><button className="admin-secondary" disabled={busy || index===data.slides.length-1} aria-label={`${index+1}. fotoğrafı sona al`} onClick={()=>move('slides',index,1)}>→</button><button className="admin-secondary" disabled={busy} onClick={()=>{setData({...data,slides:data.slides.filter(v=>v!==id)});setMessage('');}}>Seçimden çıkar</button></div></div></article>; })}</div>{!data.slides.length&&<p className="admin-empty">Başlamak için fotoğraf seçin.</p>}</section>
  <section className="admin-box admin-home-section"><div className="admin-box-heading"><div><h2>Seçilmiş projeler</h2><p>Bilgisayarda ve mobilde slaytın altında proje kartları olarak gösterilir. Açılış slaytındaki fotoğrafları değiştirmez. En fazla 12 proje.</p></div></div><div className="admin-project-choices">{projects.map(p=><label className="admin-checkbox" key={p.id}><input type="checkbox" checked={data.projects.includes(p.id)} disabled={busy||(!data.projects.includes(p.id)&&data.projects.length>=12)} onChange={e=>{setData({...data,projects:e.target.checked?[...data.projects,p.id]:data.projects.filter(id=>id!==p.id)});setMessage('');}}/>{p.title}</label>)}</div><ol className="admin-ordered-list">{data.projects.map((id,index)=><li key={id}><span>{index+1}. {projects.find(p=>p.id===id)?.title || 'Yayından kaldırılan proje'}</span><button className="admin-secondary" aria-label={`${index+1}. projeyi öne al`} disabled={busy||!index} onClick={()=>move('projects',index,-1)}>↑</button><button className="admin-secondary" aria-label={`${index+1}. projeyi sona al`} disabled={busy||index===data.projects.length-1} onClick={()=>move('projects',index,1)}>↓</button><button className="admin-secondary" disabled={busy} onClick={()=>setData({...data,projects:data.projects.filter(v=>v!==id)})}>Çıkar</button></li>)}</ol></section>
  {picker&&<MediaPicker title="Ana sayfa fotoğraflarını seç" photos={photos.filter(p=>!data.slides.includes(p.id))} multiple onClose={()=>setPicker(false)} onChoose={ids=>{ if(data.slides.length+ids.length>40){setError('En fazla 40 fotoğraf seçebilirsiniz.');return;}setData({...data,slides:[...data.slides,...ids]});setMessage('');setError('');}}/>}
  </>;
}
