'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { categories, categoryIds } from '@/content/site';
import type { ProjectRecord, ProjectSummary } from '@/lib/cms/types';
import { api, Icon, Message, thumbnail } from './ui';
export function Dashboard({ projects }: { projects: ProjectSummary[] }) {
  const active = projects.filter(p => !p.deleted);
  const counts = [{ title: 'Proje', value: active.length, icon: 'folder' }, { title: 'Fotoğraf', value: active.reduce((n, p) => n + p.photoCount, 0), icon: 'image' }, { title: 'Film', value: active.reduce((n, p) => n + p.videoCount, 0), icon: 'grid' }, { title: 'Taslak ve değişiklik', value: active.filter(p => p.status !== 'published').length, icon: 'settings' }] as const;
  return <><div className="admin-page-title"><div><h1>Genel bakış</h1><p>İşlerinize bir bütün olarak bakın.</p></div><Link className="admin-primary" href="/admin/projeler"><Icon name="folder" />Projeleri yönet</Link></div>
    <div className="admin-stats">{counts.map(item => <Link href={item.title === 'Fotoğraf' || item.title === 'Film' ? '/admin/galeri' : '/admin/projeler'} className="admin-stat" key={item.title}><div><span>{item.title}</span><Icon name={item.icon} /></div><strong>{item.value}</strong></Link>)}</div>
    <div className="admin-dashboard-grid"><section className="admin-box"><div className="admin-box-heading"><h2>Son düzenlenen projeler</h2><Link href="/admin/projeler">Tümünü gör →</Link></div><div className="admin-recent">{active.slice(0, 5).map(p => <Link href={`/admin/projeler/${p.id}`} key={p.id}>{p.cover ? <img src={thumbnail(p.cover)} alt="" /> : <span className="admin-mini-placeholder"><Icon name="image" /></span>}<div><strong>{p.title}</strong><span>{p.photoCount} fotoğraf{p.videoCount ? ` · ${p.videoCount} film` : ''}{p.status !== 'published' ? ' · Kaydedilmiş değişiklikler var' : ''}</span></div><Icon name="arrow" /></Link>)}</div></section>
    <section className="admin-guide"><span className="admin-guide-symbol">↗</span><h2>Yeni bir hikâyeye<br />yer açın.</h2><p>Bir proje oluşturun, görsellerinizi ekleyin. Son dokunuşlardan sonra yayınlayın.</p><Link href="/admin/projeler">Projeleri aç <Icon name="arrow" /></Link><div className="admin-guide-note"><Icon name="image" /><span>Fotoğrafları ve filmleri<br />birlikte yükleyebilirsiniz.</span></div></section></div>
  </>;
}
export function Projects({ projects, gallery = false }: { projects: ProjectSummary[]; gallery?: boolean }) {
  const router = useRouter(); const [query, setQuery] = useState(''), [category, setCategory] = useState('all'), [trash, setTrash] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const filtered = projects.filter(p => p.deleted === trash && p.title.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')) && (category === 'all' || p.categories.includes(category as typeof categoryIds[number]))).sort((a, b) => a.order - b.order);
  return <><div className="admin-page-title"><div><h1>{gallery ? 'Proje galerileri' : 'Projeler'}</h1><p>{gallery ? 'Fotoğraf ve filmleri kendi projelerinin içinde düzenleyin.' : 'Her proje, kendi görselleri ve hikâyesiyle.'}</p></div><button className="admin-primary" disabled={busy} onClick={async () => { setBusy(true); try { const p = await api<ProjectRecord>('projects', 'POST'); router.push(`/admin/projeler/${p.id}`); } catch (e) { setError((e as Error).message); setBusy(false); } }}><Icon name="plus" />{busy ? 'Oluşturuluyor…' : 'Yeni proje'}</button></div>
    <div className="admin-toolbar"><label className="admin-search"><span className="visually-hidden">Proje ara</span><input placeholder="Proje ara…" value={query} onChange={e => setQuery(e.target.value)} /></label><label><span className="visually-hidden">Çalışma alanı</span><select value={category} onChange={e => setCategory(e.target.value)}><option value="all">Tüm çalışma alanları</option>{categoryIds.map(id => <option key={id} value={id}>{categories[id].title.tr}</option>)}</select></label><button className={trash ? 'admin-secondary active' : 'admin-secondary'} onClick={() => setTrash(!trash)}>{trash ? '← Projelere dön' : `Çöp kutusu (${projects.filter(p => p.deleted).length})`}</button><span>{filtered.length} proje</span></div><Message error={error} />
    <div className="admin-project-grid">{filtered.map(p => <article className="admin-project-card" key={p.id}><Link href={`/admin/projeler/${p.id}${gallery ? '#gallery' : ''}`} className="admin-project-cover" aria-label={`${p.title} projesini düzenle`}>{p.cover ? <img src={thumbnail(p.cover)} alt="" loading="lazy" /> : <span><Icon name="image" />Henüz görsel eklenmedi</span>}<span className="admin-cover-arrow"><Icon name="arrow" /></span></Link><div className="admin-project-caption"><div><h2><Link href={`/admin/projeler/${p.id}${gallery ? '#gallery' : ''}`}>{p.title}</Link></h2></div><div className="admin-card-bottom"><span>{p.photoCount} fotoğraf{p.videoCount ? ` · ${p.videoCount} film` : ''}{p.status !== 'published' && !p.deleted ? ' · Henüz yayınlanmamış değişiklikler var' : ''}</span></div></div></article>)}</div>{!filtered.length && <div className="admin-empty"><Icon name="folder" /><h2>{trash ? 'Çöp kutusu boş.' : 'Proje bulunamadı.'}</h2><p>{query ? 'Arama veya filtreyi değiştirebilirsiniz.' : 'Yeni bir proje ekleyerek başlayın.'}</p></div>}
  </>;
}
